name: Publish Package to npm (provenance)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write   # Required: npm uses OIDC to generate/verify provenance

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Upgrade npm (>= 11.5.1 recommended)
      - name: Update npm
        run: npm i -g npm@latest

      # Safety check: tag must match package.json version
      - name: Verify tag === package.json version
        run: |
          TAG="${GITHUB_REF##*/}"
          PKG_VER="$(node -p "require('./package.json').version")"
          [ "$TAG" = "v$PKG_VER" ] || { echo "Tag $TAG != $PKG_VER"; exit 1; }

      # Use npm ci if lockfile exists; otherwise fallback to install
      - name: Install deps
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm install --no-audit --fund=false
          fi

      - run: npm run build --if-present
      - run: npm test --if-present
      - run: npm pack --dry-run

      # Use OIDC + provenance (to display provenance badge on npmjs.com)
      - name: Publish (OIDC + provenance)
        env:
          NPM_CONFIG_PROVENANCE: 'true'
        run: npm publish --access public --provenance
